import { render } from "preact";

import { App } from "./app/App";
import { initializeOfflineRuntime } from "./offline/runtime";
import { installPeopleGroupsReconnectRefresh, warmPeopleGroupsRuntime } from "./providers/peoplegroups";
import { initializePrivateSyncRuntime } from "./sync/runtime";
import "@fontsource-variable/newsreader";
import "@fontsource-variable/source-sans-3";
import "./styles/tokens.css";
import "./styles/base.css";
import "./styles/app.css";
import "./styles/map.css";
import "./styles/mission-map.css";
import "./styles/map-layout.css";
import "./styles/countries.css";
import "./styles/peoples.css";
import "./styles/context.css";
import "./styles/prayer.css";
import "./styles/languages.css";
import "./styles/language/resource-breakdown.css";
import "./styles/discovery.css";
import "./styles/about.css";
import "./styles/shell/overflow-guard.css";
import "./styles/foundation/loading-state.css";
import "./styles/people/index-loading.css";
import "./styles/foundation/result-pagination.css";
import "./styles/foundation/content-wrapping.css";
import "./styles/language/card-alignment.css";
import "./styles/shell/compact-navigation.css";
import "./styles/foundation/result-pagination-mobile.css";
import "./styles/foundation/loading-motion.css";
import "./styles/shell/browse-actions.css";
import "./styles/explore/layer-controls.css";
import "./styles/foundation/catalog-search.css";
import "./styles/foundation/catalog-cards.css";
import "./styles/country/catalog-cards.css";
import "./styles/people/profile-flow.css";
import "./styles/foundation/catalog-responsive.css";
import "./styles/discovery/guided-start.css";
import "./styles/people/profile-journey.css";
import "./styles/country/guided-start.css";
import "./styles/people/empty-state.css";
import "./styles/foundation/guided-responsive.css";
import "./styles/editorial/coverage.css";
import "./styles/editorial/coverage-expansion.css";
import "./styles/prayer/practice.css";
import "./styles/prayer/rotation.css";
import "./styles/prayer/session.css";
import "./styles/shell/data-state.css";
import "./styles/account/base.css";
import "./styles/shell/navigation.css";
import "./styles/people/explorer.css";
import "./styles/people/profile.css";
import "./styles/explore/map-workspace.css";
import "./styles/foundation/detail-records.css";
import "./styles/prayer/guides-and-lists.css";
import "./styles/account/ux.css";
import "./styles/comprehension.css";
import "./styles/explore/newcomer-entry.css";
import "./styles/foundation/accessibility.css";

// Start the single prepared IndexedDB read as soon as the entry module runs.
// This remains local-only and non-blocking, but it lets repeat visits have the
// shared PeopleGroups snapshot ready before the user opens a data-heavy route.
warmPeopleGroupsRuntime();
initializeOfflineRuntime();
initializePrivateSyncRuntime();
render(<App />, document.getElementById("app")!);

installPeopleGroupsReconnectRefresh();
